### ISSUE TITLE
[Algo] Prim's algorithm for minimum spanning tree [C++]

### ISSUE THREAD

**Issue by smowafy** [Sathyabama-Coding-Club/HacktoberFest2019#16]
https://en.wikipedia.org/wiki/Minimum_spanning_tree
https://en.wikipedia.org/wiki/Prim%27s_algorithm

**Comment by AkashM398** [comment]
Go ahead @smowafy

**Comment by AkashM398** [comment]
@smowafy there was a confusion, sorry about that, you are welcome to commit your own program here still 😃

**Comment by smowafy** [comment]
No worries 😀 thanks!
