### ISSUE TITLE
Attention Maitainers!!

### ISSUE THREAD

**Issue by sauravjaiswalsj** [Sathyabama-Coding-Club/HacktoberFest2019#2]
@AkashM398 @Anish-Jay You need to create issues for each algo or ds and you need to tag each issue to the label `"hacktoberfest"`which I have already reated. This will automatically help you getting pull request.

I hope this helps. once read, close the issue :smile:

**Comment by AkashM398** [comment]
Thanks for your suggestion @sauravjaiswalsj . Will do it!!
